import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { uploadFromUrlToStorage } from "@/lib/storage";
import { resolveMediaType, maxSizeFor, MAX_VIDEO_DURATION_SECONDS } from "@/lib/media-limits";
import { parseSteamScreenshotName } from "@/lib/steamScreenshot";
import { resolveGamesByAppId, scopeForGroup } from "@/lib/gameIdentify";

/**
 * Discord Botからのみ呼ばれる内部API。
 * リクエストヘッダの共有シークレットで認証する（一般ユーザーからは叩けない）。
 *
 * POST /api/discord/ingest
 * body: {
 *   discordUserId, channelId, guildId, attachmentUrl, contentType,
 *   sizeBytes, durationSeconds?, discordMessageId, postedAt, rawTag?, fileName?
 * }
 * durationSeconds は動画のみ。Botがdiscord.jsのAttachment#durationから取得して渡す。
 *
 * ゲーム判定の優先順位：
 *   1. rawTag（メッセージ本文の #eldenring 等）が指定されていれば最優先
 *      → 初出のタグなら自動でゲーム/アルバムを新規登録する（設定不要）
 *   2. rawTagが無ければチャンネルマッピング（ゲームごとにチャンネルが分かれている運用向け）
 *   3. それも無ければ添付のファイル名（Steamのスクショは <appId>_<日時>_<連番>.jpg）
 *      → ゲーム名を取り、ゲーム名が一致するアルバム → ゲーム連携のアルバム の順に探し、
 *        どちらも無ければゲーム名でアルバムを新規作成する（rawTag経由と同じ扱い）
 *   4. ファイル名から判別できなければ未分類（albumId/gameTitle は null のまま保存）
 */
export async function POST(req: Request) {
  const secret = req.headers.get("x-internal-secret");
  if (secret !== process.env.INTERNAL_API_SECRET) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }

  const body = await req.json();
  const {
    discordUserId,
    channelId,
    guildId,
    attachmentUrl,
    contentType,
    sizeBytes,
    durationSeconds,
    discordMessageId,
    postedAt,
    rawTag,
    fileName,
  } = body;

  const mediaType = resolveMediaType(contentType);
  if (!mediaType) {
    return NextResponse.json({ skipped: "unsupported content type" });
  }
  if (typeof sizeBytes === "number" && sizeBytes > maxSizeFor(mediaType)) {
    return NextResponse.json({ skipped: `exceeds ${mediaType.toLowerCase()} size limit` });
  }
  if (mediaType === "VIDEO" && durationSeconds > MAX_VIDEO_DURATION_SECONDS) {
    return NextResponse.json({ skipped: "video exceeds duration limit" });
  }

  const existing = await db.photo.findUnique({ where: { discordMessageId } });
  if (existing) {
    return NextResponse.json({ skipped: "already ingested" });
  }

  const user = await db.user.findUnique({ where: { discordUserId } });
  if (!user) {
    // 未連携ユーザーの投稿は取り込まない（設計書 4.2 参照）
    return NextResponse.json({ skipped: "user not linked" });
  }

  let gameTitle: string | null = null;
  let albumId: string | null = null;

  if (rawTag) {
    let gameTag = await db.discordGameTag.findUnique({
      where: { guildId_tag: { guildId, tag: rawTag } },
    });

    // 初出のタグは自動でゲーム/アルバムを新規登録する（管理画面での事前設定は不要）
    if (!gameTag) {
      const group = await db.group.findUnique({ where: { guildId } });
      if (!group) {
        return NextResponse.json({ skipped: "no group configured for this guild" });
      }
      const autoAlbum = await db.album.create({
        data: {
          title: rawTag,
          gameTitle: rawTag,
          isAutoGenerated: true,
          ownerId: user.id,
          groupId: group.id,
        },
      });
      gameTag = await db.discordGameTag.create({
        data: {
          guildId,
          tag: rawTag,
          gameTitle: rawTag,
          autoAlbumId: autoAlbum.id,
          registeredBy: user.id,
        },
      });
    }

    gameTitle = gameTag.gameTitle;
    albumId = gameTag.autoAlbumId;
  } else {
    // タグが無ければチャンネルマッピングにフォールバック
    const mapping = await db.discordChannelMapping.findUnique({ where: { channelId } });
    if (mapping) {
      gameTitle = mapping.gameTitle;
      albumId = mapping.autoAlbumId;
    }
    // どちらも無ければファイル名から判別する（Discordは元のファイル名を保つ）。
    // タグの付け忘れやチャンネル未設定でも、Steamのスクショなら拾える。
    if (!gameTitle) {
      const detected = await identifyByFileName(fileName, guildId, user.id);
      gameTitle = detected.gameTitle;
      albumId = detected.albumId;
    }
    // それでも当たらなければ未分類のまま保存（後からUIで手動振り分け可能）
  }

  // 撮影日時はファイル名の方が正確（投稿がプレイ後になることの方が多い）
  const screenshot = typeof fileName === "string" ? parseSteamScreenshotName(fileName) : null;

  // Discordの添付URLは失効するため、即座に永続ストレージへ移送する
  const { publicUrl, sizeBytes: storedSize } = await uploadFromUrlToStorage(
    attachmentUrl,
    mediaType
  );

  const photo = await db.photo.create({
    data: {
      mediaType,
      mediaUrl: publicUrl,
      sizeBytes: storedSize,
      durationSeconds: mediaType === "VIDEO" ? durationSeconds ?? null : null,
      uploaderId: user.id,
      albumId,
      gameTitle,
      source: "DISCORD",
      discordMessageId,
      capturedAt: screenshot?.capturedAt ?? (postedAt ? new Date(postedAt) : undefined),
    },
  });

  return NextResponse.json({ photo }, { status: 201 });
}

/**
 * 添付のファイル名からゲームを判別し、置き場所まで決める。
 *
 *   1. ファイル名からapp IDを読み、ゲーム名を取る
 *   2. ゲーム名が一致するアルバムを探す
 *   3. 無ければ、そのゲームと連携しているアルバムを探す（2と3の順はresolveGamesByAppId内）
 *   4. どちらも無ければ、ゲーム名でアルバムを新規作成する
 *
 * 4があるのはDiscord経由だけ。画面が無く、置き場所を人が選べないため
 * （rawTag経由も同じ理由で自動生成している）。手動アップロードは、判別結果を
 * 画面で見てから自分でアルバムを選べるので作らない。
 *
 * **ゲーム名が取れなかったときは作らない。** app IDだけを名前にしたアルバムが
 * 増えても意味が無く、後から掃除する方が高くつくため。
 */
async function identifyByFileName(
  fileName: unknown,
  guildId: string,
  ownerId: string
): Promise<{ gameTitle: string | null; albumId: string | null }> {
  const empty = { gameTitle: null, albumId: null };
  if (typeof fileName !== "string") return empty;

  const info = parseSteamScreenshotName(fileName);
  if (!info) return empty;

  const group = await db.group.findUnique({ where: { guildId }, select: { id: true } });
  if (!group) return empty;

  const [result] = await resolveGamesByAppId([info.appId], scopeForGroup(group.id));
  if (!result?.title) return empty;

  if (result.album) {
    return { gameTitle: result.title, albumId: result.album.id };
  }

  const created = await db.album.create({
    data: {
      title: result.title,
      gameTitle: result.title,
      steamAppId: info.appId,
      isAutoGenerated: true,
      ownerId,
      groupId: group.id,
    },
  });
  console.log(`[ingest] ゲーム名からアルバムを自動作成: ${result.title} (${created.id})`);

  return { gameTitle: result.title, albumId: created.id };
}
