import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { uploadFromUrlToStorage } from "@/lib/storage";
import { resolveMediaType, maxSizeFor, MAX_VIDEO_DURATION_SECONDS } from "@/lib/media-limits";

/**
 * Discord Botからのみ呼ばれる内部API。
 * リクエストヘッダの共有シークレットで認証する（一般ユーザーからは叩けない）。
 *
 * POST /api/discord/ingest
 * body: {
 *   discordUserId, channelId, guildId, attachmentUrl, contentType,
 *   sizeBytes, durationSeconds?, discordMessageId, postedAt, rawTag?
 * }
 * durationSeconds は動画のみ。Botがdiscord.jsのAttachment#durationから取得して渡す。
 *
 * ゲーム判定の優先順位：
 *   1. rawTag（メッセージ本文の #eldenring 等）が指定されていれば最優先
 *      → 初出のタグなら自動でゲーム/アルバムを新規登録する（設定不要）
 *   2. rawTagが無ければチャンネルマッピング（ゲームごとにチャンネルが分かれている運用向け）
 *   3. どちらも無ければ未分類（albumId/gameTitle は null のまま保存）
 */
export async function POST(req: Request) {
  const secret = req.headers.get("x-internal-secret");
  if (secret !== process.env.INTERNAL_API_SECRET) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }

  const body = await req.json();
  const {
    discordUserId,
    channelId,
    guildId,
    attachmentUrl,
    contentType,
    sizeBytes,
    durationSeconds,
    discordMessageId,
    postedAt,
    rawTag,
  } = body;

  const mediaType = resolveMediaType(contentType);
  if (!mediaType) {
    return NextResponse.json({ skipped: "unsupported content type" });
  }
  if (typeof sizeBytes === "number" && sizeBytes > maxSizeFor(mediaType)) {
    return NextResponse.json({ skipped: `exceeds ${mediaType.toLowerCase()} size limit` });
  }
  if (mediaType === "VIDEO" && durationSeconds > MAX_VIDEO_DURATION_SECONDS) {
    return NextResponse.json({ skipped: "video exceeds duration limit" });
  }

  const existing = await db.photo.findUnique({ where: { discordMessageId } });
  if (existing) {
    return NextResponse.json({ skipped: "already ingested" });
  }

  const user = await db.user.findUnique({ where: { discordUserId } });
  if (!user) {
    // 未連携ユーザーの投稿は取り込まない（設計書 4.2 参照）
    return NextResponse.json({ skipped: "user not linked" });
  }

  let gameTitle: string | null = null;
  let albumId: string | null = null;

  if (rawTag) {
    let gameTag = await db.discordGameTag.findUnique({
      where: { guildId_tag: { guildId, tag: rawTag } },
    });

    // 初出のタグは自動でゲーム/アルバムを新規登録する（管理画面での事前設定は不要）
    if (!gameTag) {
      const autoAlbum = await db.album.create({
        data: {
          title: rawTag,
          gameTitle: rawTag,
          isAutoGenerated: true,
          ownerId: user.id,
        },
      });
      gameTag = await db.discordGameTag.create({
        data: {
          guildId,
          tag: rawTag,
          gameTitle: rawTag,
          autoAlbumId: autoAlbum.id,
          registeredBy: user.id,
        },
      });
    }

    gameTitle = gameTag.gameTitle;
    albumId = gameTag.autoAlbumId;
  } else {
    // タグが無ければチャンネルマッピングにフォールバック
    const mapping = await db.discordChannelMapping.findUnique({ where: { channelId } });
    if (mapping) {
      gameTitle = mapping.gameTitle;
      albumId = mapping.autoAlbumId;
    }
    // どちらも無ければ未分類のまま保存（後からUIで手動振り分け可能）
  }

  // Discordの添付URLは失効するため、即座に永続ストレージへ移送する
  const { publicUrl, sizeBytes: storedSize } = await uploadFromUrlToStorage(
    attachmentUrl,
    mediaType
  );

  const photo = await db.photo.create({
    data: {
      mediaType,
      mediaUrl: publicUrl,
      sizeBytes: storedSize,
      durationSeconds: mediaType === "VIDEO" ? durationSeconds ?? null : null,
      uploaderId: user.id,
      albumId,
      gameTitle,
      source: "DISCORD",
      discordMessageId,
      capturedAt: postedAt ? new Date(postedAt) : undefined,
    },
  });

  return NextResponse.json({ photo }, { status: 201 });
}
