import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { invalidateAlbumPhotos } from "@/lib/cacheTags";
import { touchAlbum } from "@/lib/albumTouch";
import { logActivity } from "@/lib/activityLog";
import { uploadFromUrlToStorage } from "@/lib/storage";
import { resolveMediaType, maxSizeFor, MAX_VIDEO_DURATION_SECONDS } from "@/lib/media-limits";
import { parseSteamScreenshotName } from "@/lib/steamScreenshot";
import { resolveOrCreateAlbum } from "@/lib/gameIdentify";

/**
 * Discord Botからのみ呼ばれる内部API。
 * リクエストヘッダの共有シークレットで認証する（一般ユーザーからは叩けない）。
 *
 * POST /api/discord/ingest
 * body: {
 *   discordUserId, channelId, guildId, attachmentUrl, contentType,
 *   sizeBytes, durationSeconds?, discordMessageId, postedAt, rawTag?, fileName?
 * }
 * **durationSeconds は実際には送られてこない。** discord.jsの Attachment#duration は
 * ボイスメッセージ用で、動画の添付には長さの情報が無い。下の判定は将来送れるように
 * なった場合の受け皿として残しているだけで、いまDiscord経由の動画を守っているのは
 * サイズ上限だけ（Discord自身の添付上限もあるので実害は小さい）。
 *
 * ゲーム判定の優先順位：
 *   1. rawTag（メッセージ本文の #eldenring 等）が指定されていれば最優先
 *      → 初出のタグなら自動でゲーム/アルバムを新規登録する（設定不要）
 *   2. rawTagが無ければチャンネルマッピング（ゲームごとにチャンネルが分かれている運用向け）
 *   3. それも無ければ添付のファイル名（Steamのスクショは <appId>_<日時>_<連番>.jpg）
 *      → ゲーム名を取り、ゲーム名が一致するアルバム → ゲーム連携のアルバム の順に探し、
 *        どちらも無ければゲーム名でアルバムを新規作成する（rawTag経由と同じ扱い）
 *   4. ファイル名から判別できなければ未分類（albumId/gameTitle は null のまま保存）
 */
// **動画のバイナリはこの関数を丸ごと通る。** Discordの一時URLから落として
// R2へ上げ直すため（添付URLは失効するので、そのまま保存できない）。
// 上限を30MB→100MBに上げた分だけ所要時間も伸びるので、既定（Hobbyで10秒）では
// 途中で打ち切られうる。60秒はこのプランで指定できる上限。
export const maxDuration = 60;

export async function POST(req: Request) {
  const secret = req.headers.get("x-internal-secret");
  if (secret !== process.env.INTERNAL_API_SECRET) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }

  const body = await req.json();
  const {
    discordUserId,
    channelId,
    guildId,
    attachmentUrl,
    contentType,
    sizeBytes,
    durationSeconds,
    discordMessageId,
    postedAt,
    rawTag,
    fileName,
  } = body;

  const mediaType = resolveMediaType(contentType);
  if (!mediaType) {
    return NextResponse.json({ skipped: "unsupported content type" });
  }
  if (typeof sizeBytes === "number" && sizeBytes > maxSizeFor(mediaType)) {
    return NextResponse.json({ skipped: `exceeds ${mediaType.toLowerCase()} size limit` });
  }
  if (mediaType === "VIDEO" && typeof durationSeconds === "number" && durationSeconds > MAX_VIDEO_DURATION_SECONDS) {
    return NextResponse.json({ skipped: "video exceeds duration limit" });
  }

  const existing = await db.photo.findUnique({ where: { discordMessageId } });
  if (existing) {
    return NextResponse.json({ skipped: "already ingested" });
  }

  const user = await db.user.findUnique({ where: { discordUserId } });
  if (!user) {
    // 未連携ユーザーの投稿は取り込まない（設計書 4.2 参照）
    return NextResponse.json({ skipped: "user not linked" });
  }

  let gameTitle: string | null = null;
  let albumId: string | null = null;

  if (rawTag) {
    let gameTag = await db.discordGameTag.findUnique({
      where: { guildId_tag: { guildId, tag: rawTag } },
    });

    // 初出のタグは自動でゲーム/アルバムを新規登録する（管理画面での事前設定は不要）
    if (!gameTag) {
      const group = await db.group.findUnique({ where: { guildId } });
      if (!group) {
        return NextResponse.json({ skipped: "no group configured for this guild" });
      }
      const autoAlbum = await db.album.create({
        data: {
          title: rawTag,
          gameTitle: rawTag,
          isAutoGenerated: true,
          ownerId: user.id,
          groupId: group.id,
        },
      });
      await logActivity({
        kind: "album.created",
        targetId: autoAlbum.id,
        targetName: autoAlbum.title,
        groupId: group.id,
        actorId: user.id,
        occurredAt: autoAlbum.createdAt,
        detail: { auto: true },
      });
      gameTag = await db.discordGameTag.create({
        data: {
          guildId,
          tag: rawTag,
          gameTitle: rawTag,
          autoAlbumId: autoAlbum.id,
          registeredBy: user.id,
        },
      });
    }

    gameTitle = gameTag.gameTitle;
    albumId = gameTag.autoAlbumId;
  } else {
    // タグが無ければチャンネルマッピングにフォールバック
    const mapping = await db.discordChannelMapping.findUnique({ where: { channelId } });
    if (mapping) {
      gameTitle = mapping.gameTitle;
      albumId = mapping.autoAlbumId;
    }
    // どちらも無ければファイル名から判別する（Discordは元のファイル名を保つ）。
    // タグの付け忘れやチャンネル未設定でも、Steamのスクショなら拾える。
    if (!gameTitle) {
      const detected = await identifyByFileName(fileName, guildId, user.id);
      gameTitle = detected.gameTitle;
      albumId = detected.albumId;
    }
    // それでも当たらなければ未分類のまま保存（後からUIで手動振り分け可能）
  }

  // 撮影日時はファイル名の方が正確（投稿がプレイ後になることの方が多い）
  const screenshot = typeof fileName === "string" ? parseSteamScreenshotName(fileName) : null;

  // Discordの添付URLは失効するため、即座に永続ストレージへ移送する
  const { publicUrl, sizeBytes: storedSize } = await uploadFromUrlToStorage(
    attachmentUrl,
    mediaType
  );

  const photo = await db.photo.create({
    data: {
      mediaType,
      mediaUrl: publicUrl,
      sizeBytes: storedSize,
      durationSeconds: mediaType === "VIDEO" ? durationSeconds ?? null : null,
      uploaderId: user.id,
      albumId,
      gameTitle,
      source: "DISCORD",
      discordMessageId,
      capturedAt: screenshot?.capturedAt ?? (postedAt ? new Date(postedAt) : undefined),
    },
  });

  // ゲームが分からないままなら、Botが投稿者に聞けるよう知らせる
  // Botからの投稿もアルバム詳細・グループ詳細に出るので取り直させる
  let groupId: string | null = null;
  if (photo.albumId) {
    // **アルバムの updatedAt も進める**（投稿されたアルバムが更新順で上に来るように。
    // 理由は lib/albumTouch.ts）。groupId を返すので、ここは往復が増えない
    groupId = await touchAlbum(photo.albumId);
    invalidateAlbumPhotos(photo.albumId, groupId);
  }

  // **未分類（albumId が null）だと groupId も null になる。**
  // そのままだとグループの週次まとめに一生出てこないので、後で振り分けられた時点で
  // /api/photos/assign-album がこの行の groupId を埋め直す。
  //
  // occurredAt はファイル名から読んだ撮影日時（無ければDiscordの投稿時刻）。
  // 「先週遊んだぶんをまとめて投稿」でもカレンダー上は遊んだ日に並ぶ。
  await logActivity({
    kind: "photo.created",
    targetId: photo.id,
    targetName: photo.gameTitle,
    groupId,
    actorId: user.id,
    occurredAt: photo.capturedAt ?? photo.createdAt,
    detail: { mediaType: photo.mediaType, source: photo.source },
  });

  return NextResponse.json({ photo, needsGame: !gameTitle }, { status: 201 });
}

/**
 * 添付のファイル名からゲームを判別し、置き場所まで決める。
 *
 * ゲームが分かるのはSteamからダウンロードした形（`<appId>_<連番>.jpg`）だけ。
 * PCのSteamフォルダ内の名前は日時しか持たないため、ここでは判別できない
 * （app IDはフォルダ側にあり、ブラウザからは取れない）。
 */
async function identifyByFileName(
  fileName: unknown,
  guildId: string,
  ownerId: string
): Promise<{ gameTitle: string | null; albumId: string | null }> {
  const empty = { gameTitle: null, albumId: null };
  if (typeof fileName !== "string") return empty;

  const info = parseSteamScreenshotName(fileName);
  if (info?.appId == null) return empty;

  const group = await db.group.findUnique({ where: { guildId }, select: { id: true } });
  if (!group) return empty;

  return (await resolveOrCreateAlbum(info.appId, group.id, ownerId)) ?? empty;
}
