import { NextResponse } from "next/server";
import { db } from "@/lib/db";

/**
 * Discord Botの/tagコマンドからのみ呼ばれる内部API。
 * リクエストヘッダの共有シークレットで認証する（一般ユーザーからは叩けない）。
 *
 * POST /api/discord/tag
 * body: { discordUserId, guildId, gameTitle, tag }
 *
 * 発言者が直近に投稿した写真（未タグ付けかどうかは問わない）に、
 * ハッシュタグ取り込みと同じDiscordGameTagレコードを使ってゲームタグ/アルバムを付け直す。
 */
const RECENT_PHOTO_WINDOW_MS = 10 * 60 * 1000;

export async function POST(req: Request) {
  const secret = req.headers.get("x-internal-secret");
  if (secret !== process.env.INTERNAL_API_SECRET) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }

  const body = await req.json();
  const { discordUserId, guildId, gameTitle, tag } = body;
  if (!discordUserId || !guildId || !gameTitle || !tag) {
    return NextResponse.json({ error: "invalid payload" }, { status: 400 });
  }

  const user = await db.user.findUnique({ where: { discordUserId } });
  if (!user) {
    return NextResponse.json({ error: "user not linked" }, { status: 404 });
  }

  const photo = await db.photo.findFirst({
    where: {
      uploaderId: user.id,
      source: "DISCORD",
      createdAt: { gte: new Date(Date.now() - RECENT_PHOTO_WINDOW_MS) },
    },
    orderBy: { createdAt: "desc" },
  });
  if (!photo) {
    return NextResponse.json({ error: "no recent photo found" }, { status: 404 });
  }

  let gameTag = await db.discordGameTag.findUnique({
    where: { guildId_tag: { guildId, tag } },
  });

  // 初出のタグは #hashtag による自動取り込みと同様、その場でゲーム/アルバムを新規登録する
  if (!gameTag) {
    const autoAlbum = await db.album.create({
      data: {
        title: gameTitle,
        gameTitle,
        isAutoGenerated: true,
        ownerId: user.id,
      },
    });
    gameTag = await db.discordGameTag.create({
      data: {
        guildId,
        tag,
        gameTitle,
        autoAlbumId: autoAlbum.id,
        registeredBy: user.id,
      },
    });
  }

  const updated = await db.photo.update({
    where: { id: photo.id },
    data: { gameTitle: gameTag.gameTitle, albumId: gameTag.autoAlbumId },
  });

  return NextResponse.json({ photo: updated });
}
