import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { db } from "@/lib/db";

// GET /api/discord/channel-mappings … 対応表の一覧
export async function GET() {
  const mappings = await db.discordChannelMapping.findMany({
    orderBy: { createdAt: "desc" },
  });
  return NextResponse.json({ mappings });
}

// POST /api/discord/channel-mappings … チャンネルとゲーム/アルバムの紐付け登録
// 例: 「#elden-ring」チャンネル → 「エルデンリング」の自動アルバム
export async function POST(req: Request) {
  const session = await getServerSession(authOptions);
  const user = session?.user?.email
    ? await db.user.findUnique({ where: { email: session.user.email } })
    : null;
  if (!user) return NextResponse.json({ error: "unauthorized" }, { status: 401 });

  const body = await req.json(); // { guildId, channelId, gameTitle }

  // このチャンネル専用の自動アルバムがなければ作成する
  let album = await db.album.findFirst({
    where: { isAutoGenerated: true, gameTitle: body.gameTitle, ownerId: user.id },
  });
  if (!album) {
    const group = await db.group.findUnique({ where: { guildId: body.guildId } });
    if (!group) {
      return NextResponse.json({ error: "no group configured for this guild" }, { status: 404 });
    }
    album = await db.album.create({
      data: {
        title: body.gameTitle,
        gameTitle: body.gameTitle,
        isAutoGenerated: true,
        ownerId: user.id,
        groupId: group.id,
      },
    });
  }

  const mapping = await db.discordChannelMapping.create({
    data: {
      guildId: body.guildId,
      channelId: body.channelId,
      gameTitle: body.gameTitle,
      autoAlbumId: album.id,
      registeredBy: user.id,
    },
  });

  return NextResponse.json({ mapping }, { status: 201 });
}
