import type { Prisma } from "@prisma/client";
import { db } from "./db";
import { getSteamAppNameJa, searchSteamGames } from "./steam";
import { getOrFetchExternalGameData } from "./externalGameCache";

export type IdentifiedGame = {
  appId: number;
  title: string | null;
  album: { id: string; title: string } | null;
};

/**
 * 探索範囲。手動アップロードとDiscord取り込みで「誰から見えるか」が違うため、
 * 呼び出し側から条件を渡す。
 *   - 手動:    自分が所有/参加しているアルバム・グループ
 *   - Discord: そのギルドに紐づくグループ
 */
export type IdentifyScope = {
  albumWhere: Prisma.AlbumWhereInput;
  groupGameWhere: Prisma.GroupGameWhereInput;
};

/**
 * Steamのapp IDを「表示できるゲーム名」と「既にあるアルバム」に変える。
 *
 * 名前は**アプリが既に知っているものを優先**する。GroupGameやAlbumに入っている
 * タイトルを使えばSteamに問い合わせずに済むうえ、グループ内で表記が揃うため。
 * どこにも無いゲームのときだけappdetailsを引く。
 *
 * アルバムは2経路で探す。Album.steamAppIdが入っていればそれ、入っていなくても
 * GroupGame経由で紐付いたアルバムを辿る（アルバム側にIDが無い作り方もあるため）。
 */
export async function resolveGamesByAppId(
  appIds: number[],
  scope: IdentifyScope
): Promise<IdentifiedGame[]> {
  if (appIds.length === 0) return [];

  const [albums, groupGames] = await Promise.all([
    db.album.findMany({
      where: { steamAppId: { in: appIds }, ...scope.albumWhere },
      orderBy: { updatedAt: "desc" },
      select: { id: true, title: true, gameTitle: true, steamAppId: true },
    }),
    db.groupGame.findMany({
      where: { steamAppId: { in: appIds }, ...scope.groupGameWhere },
      select: {
        steamAppId: true,
        title: true,
        album: { select: { id: true, title: true } },
      },
    }),
  ]);

  const resolved = await Promise.all(
    appIds.map(async (appId) => {
      const album = albums.find((a) => a.steamAppId === appId);
      const game = groupGames.find((g) => g.steamAppId === appId);
      const known = game?.title ?? album?.gameTitle ?? null;

      return {
        appId,
        title: known ?? (await getSteamAppNameJa(appId)),
        byAppId: album ? { id: album.id, title: album.title } : null,
        byGameLink: game?.album ? { id: game.album.id, title: game.album.title } : null,
      };
    })
  );

  // ゲーム名で紐づくアルバムも探す。app IDを持たないアルバム（Discordのタグから
  // 自動生成されたものなど）は、名前でしか辿れないため。
  const byName = await findAlbumsByGameName(
    resolved.map((r) => r.title).filter((t): t is string => Boolean(t)),
    scope
  );

  return resolved.map((r) => ({
    appId: r.appId,
    title: r.title,
    // 探す順番：ゲーム名が一致するアルバム → app IDが入っているアルバム → ゲーム連携のアルバム
    album:
      (r.title ? byName.get(r.title.toLowerCase()) ?? null : null) ??
      r.byAppId ??
      r.byGameLink,
  }));
}

/** ゲーム名（Album.gameTitle）が一致するアルバムを引く。大文字小文字は区別しない */
async function findAlbumsByGameName(
  titles: string[],
  scope: IdentifyScope
): Promise<Map<string, { id: string; title: string }>> {
  const found = new Map<string, { id: string; title: string }>();
  if (titles.length === 0) return found;

  const albums = await db.album.findMany({
    where: {
      OR: titles.map((t) => ({ gameTitle: { equals: t, mode: "insensitive" as const } })),
      ...scope.albumWhere,
    },
    orderBy: { updatedAt: "desc" },
    select: { id: true, title: true, gameTitle: true },
  });

  // 同名が複数あれば、更新が新しい方を残す（orderByの並び順に依存）
  for (const a of albums) {
    const key = a.gameTitle?.toLowerCase();
    if (key && !found.has(key)) found.set(key, { id: a.id, title: a.title });
  }
  return found;
}

/**
 * app IDから「タグに使うゲーム名」と「置き場所のアルバム」を決める。
 * 見つからなければゲーム名でアルバムを作る。
 *
 * ファイル名からの判別とBotへの返答（どちらもDiscord経由）で同じ結果になるよう、
 * 置き場所を決める処理はここに1つだけ置く。
 *
 * **ゲーム名が取れなかったときは何もしない。** app IDだけを名前にしたアルバムが
 * 増えても意味が無く、後から掃除する方が高くつくため。
 */
export async function resolveOrCreateAlbum(
  appId: number,
  groupId: string,
  ownerId: string
): Promise<{ gameTitle: string; albumId: string } | null> {
  const [result] = await resolveGamesByAppId([appId], scopeForGroup(groupId));
  if (!result?.title) return null;

  if (result.album) {
    return { gameTitle: result.title, albumId: result.album.id };
  }

  const created = await db.album.create({
    data: {
      title: result.title,
      gameTitle: result.title,
      steamAppId: appId,
      isAutoGenerated: true,
      ownerId,
      groupId,
    },
  });
  console.log(`[album] ゲーム名からアルバムを自動作成: ${result.title} (${created.id})`);

  // ゲーム詳細からアルバムへ辿れるようにする。既に別のアルバムと紐付いている場合は触らない
  await db.groupGame.updateMany({
    where: { groupId, steamAppId: appId, albumId: null },
    data: { albumId: created.id },
  });

  return { gameTitle: result.title, albumId: created.id };
}

/**
 * ゲーム名で検索して、必要ならゲームリストへの登録とアルバム作成まで行う。
 *
 * Botの「どのゲーム？」で自由入力が選ばれたときの経路。まだグループのゲームリストに
 * 無いゲームでも、名前を打てばそのまま置き場所まで用意できるようにする。
 *
 * `searchSteamGames` は `type: "app"` 以外（パッケージ・バンドル）を除いてくれるので、
 * app IDでない別体系のIDが紛れ込むことはない。
 */
export async function resolveByNameAndCreate(
  query: string,
  groupId: string,
  ownerId: string
): Promise<{ gameTitle: string; albumId: string; steamAppId: number } | null> {
  const results = await searchSteamGames(query);
  const hit = results[0];
  if (!hit) return null;

  await ensureGroupGame(hit.appId, hit.name, groupId, ownerId);

  const resolved = await resolveOrCreateAlbum(hit.appId, groupId, ownerId);
  if (!resolved) return null;

  return { ...resolved, steamAppId: hit.appId };
}

/**
 * グループのゲームリストにまだ無ければ追加する。
 *
 * カバー画像は必ず appdetails の値を使う（`getOrFetchExternalGameData` 経由）。
 * `steam/apps/<id>/header.jpg` の組み立ては新しめのタイトルで404になる。
 *
 * ステータスをPLAYINGにしているのは、スクショが上がっている＝今遊んでいるため。
 * 既定のWISHLIST（欲しいものリスト）では実態と合わない。
 */
async function ensureGroupGame(
  steamAppId: number,
  title: string,
  groupId: string,
  addedById: string
): Promise<void> {
  const existing = await db.groupGame.findUnique({
    where: { groupId_steamAppId: { groupId, steamAppId } },
    select: { id: true },
  });
  if (existing) return;

  const { headerImage, ...external } = await getOrFetchExternalGameData(steamAppId, title);

  await db.groupGame.create({
    data: {
      groupId,
      steamAppId,
      title,
      coverUrl: headerImage,
      status: "PLAYING",
      addedById,
      ...external,
    },
  });
  console.log(`[game] ゲームリストに追加: ${title} (${steamAppId})`);
}

/** 手動アップロード用。自分が所有しているか参加しているものだけを見る */
export function scopeForUser(userId: string): IdentifyScope {
  const mine = { OR: [{ ownerId: userId }, { members: { some: { userId } } }] };
  return {
    albumWhere: mine,
    groupGameWhere: { group: mine },
  };
}

/** Discord取り込み用。そのギルドに紐づくグループの中だけを見る */
export function scopeForGroup(groupId: string): IdentifyScope {
  return {
    albumWhere: { groupId },
    groupGameWhere: { groupId },
  };
}
